### ISSUE TITLE
`application/x-subrip` (`.srt` files) not previewed

### ISSUE THREAD

**Issue by xfzv** [boydaihungst/mediainfo.yazi#3]
I have some `.srt` subtitles files with `application/x-subrip` MIME type:

```console
% file -bL --mime-type test.srt
application/x-subrip
```

The file structure (nothing unusual I guess?):

```
1
00:00:00,100 --> 00:00:10,000
this is subtitle a line

2
[...]
```

In `~/.config/yazi.toml`, I'm using:

```toml
prepend_preloaders = [
  { mime = "{audio,image,video}/*", run = "mediainfo" },
  { mime = "application/{subrip,x-subrip}", run = "mediainfo" },
]
```

However, when hovering `test.srt` file, all I'm getting in the preview pane is:

![Image](https://github.com/user-attachments/assets/6ed2b6d8-3fc0-493d-96ca-3e6377516925)

Not sure if that's normal, I'd expect to get a preview similar to the one in the `README`:

![Image](https://github.com/user-attachments/assets/659a48e6-bfbc-4624-b35d-9c52a7bfbbc1)

**Comment by boydaihungst** [comment]
`x-` mimetype is obsoleted. 
U needs to add previewers:

```toml
[plugin]
  prepend_preloaders = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
  ]
  prepend_previewers = [
    # Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
  ]
```
